#https://github.com/facebookresearch/SlowFast/blob/9839d1318c0ae17bd82c6a121e5640aebc67f126/configs/Kinetics/MVIT_B_32x3_CONV.yaml
TRAIN:
  ENABLE: True
  DATASET: assembly101
  BATCH_SIZE: 512 # batch_size: int(cfg.TRAIN.BATCH_SIZE / max(1, cfg.NUM_GPUS))
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 2
  AUTO_RESUME: True
  CLIP_GRADIENT_NORM: 1
  GRADIENT_ACCUMULATION: 1
  PARTIAL_DS: 1
  USE_POSE: False
  USE_MASK: False
  MULTITASK: False
  NUM_SEGMENTS: 4
  CHECKPOINT_FILE_PATH: /data1/xbs/slowfast/checkpoints/MViTv2_S_16x4_k400_f302660347.pyth
  CHECKPOINT_IN_INIT: False
PROMPT:
  ENABLE: True
  NUM_TOKENS: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
  # PROJECT_DIM: 96
  DROPOUT: 0.1
  DIM_MUL: None  #[[1, 2.0], [3, 2.0], [14, 2.0]]
  DEEP: False
  SPECIFIC: True
  AGNOSTIC: False
  STAGE2: False
PATCHPROMPT:
  ENABLE: True
  CROPPED_PATH: /data1/xbs/data/assembly101_rgb_cropped
  PROMPT_SIZE: 1
DATA:
  PATH_TO_DATA_DIR: /data1/xbs/data/assembly101_rgb/
  PATH_TO_ANNOTATIONS: /data1/xbs/data/multiview_2_first
  INPUT_CHANNEL_NUM: [3]
  NUM_FRAMES: 4
MVIT:
  ZERO_DECAY_POS_CLS: False
  USE_ABS_POS: False
  REL_POS_SPATIAL: True
  REL_POS_TEMPORAL: True
  DEPTH: 16
  NUM_HEADS: 1
  EMBED_DIM: 96
  PATCH_KERNEL: (3, 7, 7)
  PATCH_STRIDE: (2, 4, 4)
  PATCH_PADDING: (1, 3, 3)
  MLP_RATIO: 4.0
  QKV_BIAS: True
  DROPPATH_RATE: 0.2
  NORM: "layernorm"
  MODE: "conv"
  CLS_EMBED_ON: True
  DIM_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  POOL_KVQ_KERNEL: [3, 3, 3]
  POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
  POOL_Q_STRIDE: [[0, 1, 1, 1], [1, 1, 2, 2], [2, 1, 1, 1], [3, 1, 2, 2], [4, 1, 1, 1], [5, 1, 1, 1], [6, 1, 1, 1], [7, 1, 1, 1], [8, 1, 1, 1], [9, 1, 1, 1], [10, 1, 1, 1], [11, 1, 1, 1], [12, 1, 1, 1], [13, 1, 1, 1], [14, 1, 2, 2], [15, 1, 1, 1]]
  DROPOUT_RATE: 0.0
  DIM_MUL_IN_ATT: True
  RESIDUAL_POOLING: True
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
  # NORM_TYPE: sync_batchnorm
  # NUM_SYNC_DEVICES: 4
SOLVER:
  BASE_LR: 1e-3
  BASE_LR_SCALE_NUM_SHARDS: True
  CLIP_GRAD_L2NORM: 1.0
  # LR_POLICY: steps_with_relative_lrs
  # LRS: [1, 0.1, 0.01, 0.001, 0.0001, 0.00001]
  # STEPS: [0, 14, 22]
  LR_POLICY: cosine
  COSINE_END_LR: 1e-5
  COSINE_AFTER_WARMUP: True
  MAX_EPOCH: 50
  WARMUP_EPOCHS: 0
  MOMENTUM: 0.9
  WARMUP_START_LR: 1e-5
  WEIGHT_DECAY: 0.05
  ZERO_WD_1D_PARAM: True
  OPTIMIZING_METHOD: adamw
MODEL:
  MODEL_NAME: MPromptViT_masking
  NUM_CLASSES: 142
  ARCH: mvit
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TSM:
  NUM_SEGMENTS: 4
  NEW_LENGTH: 1
  MODALITY: RGB
ASSEMBLY:
  MODALITY: mono
TEST:
  ENABLE: True
  DATASET: assembly101
  BATCH_SIZE: 512
  NUM_ENSEMBLE_VIEWS: 5
  NUM_SPATIAL_CROPS: 1
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
TENSORBOARD:
  ENABLE: False
# GPU_ID: 4
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /data1/xbs/results/Assembly101_DDL/shallow_stage1
LOG_MODEL_INFO: False
LOG_PERIOD: 50
NUM_GPUS: 4
DEBUG: False